repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v1.11.0
  hooks:
  - id: pyupgrade
    args: [--py36-plus]
- repo: https://github.com/ambv/black
  rev: 18.9b0
  hooks:
  - id: black
    language_version: python3.6
    args: [--py36]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: flake8
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.660
  hooks:
  - id: mypy
- repo: https://github.com/asottile/blacken-docs
  rev: v0.3.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==18.9b0]
    args: [--py36]
