# Config file for automatic testing at travis-ci.org

language: python

# Faster, containerized builds
sudo: false

python:
  - "3.6"
  - "3.5"
  - "2.7"

install:
  - pip install -U .
  - pip install -r dev-requirements.txt

script: invoke test
